/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import Model.Actividad;
import Model.Dia;
import java.awt.Dialog;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Alejandro
 */
public class FormActividadJDialog extends javax.swing.JDialog {

    private Integer idActividad;
    private static final DateTimeFormatter TIME_FORMAT
            = DateTimeFormatter.ofPattern("HH:mm");

    /**
     * Creates new form FormActividadJDialog
     */
    public FormActividadJDialog(java.awt.Window parent) {
        super(parent, Dialog.ModalityType.APPLICATION_MODAL);
        initComponents();
        configurarSpinnersHora();
        configurarSaltosMinutos();
        setSize(700, 500);
        setResizable(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonActAceptar = new javax.swing.JButton();
        jButtonActCancelar = new javax.swing.JButton();
        jTextFieldActNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaActDesc = new javax.swing.JTextArea();
        jSpinnerActAforo = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBoxL = new javax.swing.JCheckBox();
        jCheckBoxX = new javax.swing.JCheckBox();
        jCheckBoxM = new javax.swing.JCheckBox();
        jCheckBoxJ = new javax.swing.JCheckBox();
        jCheckBoxV = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxS = new javax.swing.JCheckBox();
        jCheckBoxD = new javax.swing.JCheckBox();
        jSpinnerHoraFin = new javax.swing.JSpinner();
        jSpinnerHoraIni = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin,. Datos de actividad dirigida");

        jButtonActAceptar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonActAceptar.setText("Aceptar");

        jButtonActCancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonActCancelar.setText("Cancelar");
        jButtonActCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActCancelarActionPerformed(evt);
            }
        });

        jTextFieldActNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActNombreActionPerformed(evt);
            }
        });

        jTextAreaActDesc.setColumns(20);
        jTextAreaActDesc.setRows(5);
        jScrollPane1.setViewportView(jTextAreaActDesc);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Actividad: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Comienza a las: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Termina a las: ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Aforo máx.: ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Descripción: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("NUEVA ACTIVDAD DIRIGIDA");

        jCheckBoxL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxL.setText("L");

        jCheckBoxX.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxX.setText("X");

        jCheckBoxM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxM.setText("M");

        jCheckBoxJ.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxJ.setText("J");

        jCheckBoxV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxV.setText("V");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Días de impartición: ");

        jCheckBoxS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxS.setText("S");

        jCheckBoxD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckBoxD.setText("D");
        jCheckBoxD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jButtonActCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)
                                .addComponent(jButtonActAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxL)
                                .addGap(1, 1, 1)
                                .addComponent(jCheckBoxM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxJ)
                                .addGap(3, 3, 3)
                                .addComponent(jCheckBoxV)
                                .addGap(0, 0, 0)
                                .addComponent(jCheckBoxS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxD))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldActNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jSpinnerHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSpinnerHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerActAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerHoraIni, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jTextFieldActNombre))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerActAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBoxL)
                    .addComponent(jCheckBoxM)
                    .addComponent(jCheckBoxX)
                    .addComponent(jCheckBoxJ)
                    .addComponent(jCheckBoxV)
                    .addComponent(jCheckBoxS)
                    .addComponent(jCheckBoxD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButtonActCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActCancelarActionPerformed
        dispose();    }//GEN-LAST:event_jButtonActCancelarActionPerformed

    private void jCheckBoxDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDActionPerformed

    private void jTextFieldActNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActAceptar;
    private javax.swing.JButton jButtonActCancelar;
    private javax.swing.JCheckBox jCheckBoxD;
    private javax.swing.JCheckBox jCheckBoxJ;
    private javax.swing.JCheckBox jCheckBoxL;
    private javax.swing.JCheckBox jCheckBoxM;
    private javax.swing.JCheckBox jCheckBoxS;
    private javax.swing.JCheckBox jCheckBoxV;
    private javax.swing.JCheckBox jCheckBoxX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerActAforo;
    private javax.swing.JSpinner jSpinnerHoraFin;
    private javax.swing.JSpinner jSpinnerHoraIni;
    private javax.swing.JTextArea jTextAreaActDesc;
    private javax.swing.JTextField jTextFieldActNombre;
    // End of variables declaration//GEN-END:variables
public String getJTextFieldActNombre() {
        return jTextFieldActNombre.getText();
    }

    public String getJTextAreaActDesc() {
        return jTextAreaActDesc.getText();
    }

    public int getJSpinnerActAforo() {
        return (int) jSpinnerActAforo.getValue();
    }

    public JButton getJButtonActAceptar() {
        return jButtonActAceptar;
    }

    public JButton getJButtonActCancelar() {
        return jButtonActCancelar;
    }

    public void setActividad(Actividad actividad) {
        this.idActividad = actividad.getIdActividad();
        jTextFieldActNombre.setText(actividad.getNombre());
        jTextAreaActDesc.setText(actividad.getDescripcion());

        jSpinnerHoraIni.setValue(
                java.sql.Time.valueOf(actividad.getHoraInicio())
        );

        jSpinnerHoraFin.setValue(
                java.sql.Time.valueOf(actividad.getHoraFin())
        );

        jSpinnerActAforo.setValue(actividad.getAforoMaximo());;
    }

    public Integer getIdActividad() {
        return idActividad;
    }

    public boolean isLunesSeleccionado() {
        return jCheckBoxL.isSelected();
    }

    public boolean isMartesSeleccionado() {
        return jCheckBoxM.isSelected();
    }

    public boolean isMiercolesSeleccionado() {
        return jCheckBoxX.isSelected();
    }

    public boolean isJuevesSeleccionado() {
        return jCheckBoxJ.isSelected();
    }

    public boolean isViernesSeleccionado() {
        return jCheckBoxV.isSelected();
    }

    public boolean isSabadoSeleccionado() {
        return jCheckBoxS.isSelected();
    }

    public boolean isDomingoSeleccionado() {
        return jCheckBoxD.isSelected();
    }

    /**
     * Devuelve la lista de días seleccionados en el formulario.
     *
     * @param diasDisponibles lista de días desde BD
     * @return lista de días seleccionados
     */
    public List<Dia> getDiasSeleccionados(List<Dia> diasDisponibles) {

        List<Dia> seleccionados = new ArrayList<>();

        for (Dia dia : diasDisponibles) {

            String codigo = dia.getCodigo();

            if (codigo == null) {
                continue;
            }

            switch (codigo.trim()) {

                case "L":
                    if (jCheckBoxL.isSelected()) {
                        seleccionados.add(dia);
                    }
                    break;

                case "M":
                    if (jCheckBoxM.isSelected()) {
                        seleccionados.add(dia);
                    }
                    break;

                case "X":
                    if (jCheckBoxX.isSelected()) {
                        seleccionados.add(dia);
                    }
                    break;

                case "J":
                    if (jCheckBoxJ.isSelected()) {
                        seleccionados.add(dia);
                    }
                    break;

                case "V":
                    if (jCheckBoxV.isSelected()) {
                        seleccionados.add(dia);
                    }
                    break;

                case "S":
                    if (jCheckBoxS.isSelected()) {
                        seleccionados.add(dia);
                    }
                    break;

                case "D":
                    if (jCheckBoxD.isSelected()) {
                        seleccionados.add(dia);
                    }
                    break;
            }
            System.out.println("Codigo BD: '" + dia.getCodigo() + "'");
        }

        System.out.println("Seleccionados: " + seleccionados.size());

        return seleccionados;
    }

    public void marcarDias(List<Dia> dias) {

        // Limpiar primero
        jCheckBoxL.setSelected(false);
        jCheckBoxM.setSelected(false);
        jCheckBoxX.setSelected(false);
        jCheckBoxJ.setSelected(false);
        jCheckBoxV.setSelected(false);
        jCheckBoxS.setSelected(false);
        jCheckBoxD.setSelected(false);

        for (Dia d : dias) {

            if (d == null || d.getCodigo() == null) {
                continue;
            }

            switch (d.getCodigo()) {

                case "L":
                    jCheckBoxL.setSelected(true);
                    break;

                case "M":
                    jCheckBoxM.setSelected(true);
                    break;

                case "X":
                    jCheckBoxX.setSelected(true);
                    break;

                case "J":
                    jCheckBoxJ.setSelected(true);
                    break;

                case "V":
                    jCheckBoxV.setSelected(true);
                    break;

                case "S":
                    jCheckBoxS.setSelected(true);
                    break;

                case "D":
                    jCheckBoxD.setSelected(true);
                    break;

                default:
                    break;
            }
        }
    }

    private void configurarSpinnersHora() {

        SpinnerDateModel modelIni = new SpinnerDateModel();
        jSpinnerHoraIni.setModel(modelIni);
        jSpinnerHoraIni.setEditor(new JSpinner.DateEditor(jSpinnerHoraIni, "HH:mm"));

        SpinnerDateModel modelFin = new SpinnerDateModel();
        jSpinnerHoraFin.setModel(modelFin);
        jSpinnerHoraFin.setEditor(new JSpinner.DateEditor(jSpinnerHoraFin, "HH:mm"));
    }

    public LocalTime getHoraInicio() {
        Date date = (Date) jSpinnerHoraIni.getValue();
        return date.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalTime()
                .withSecond(0)
                .withNano(0);
    }

    public LocalTime getHoraFin() {
        Date date = (Date) jSpinnerHoraFin.getValue();
        return date.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalTime()
                .withSecond(0)
                .withNano(0);
    }

    private void configurarSaltosMinutos() {
        ChangeListener listener = e -> {
            JSpinner spinner = (JSpinner) e.getSource();
            Date date = (Date) spinner.getValue();

            Calendar cal = Calendar.getInstance();
            cal.setTime(date);

            int minutos = cal.get(Calendar.MINUTE);
            cal.set(Calendar.MINUTE, (minutos / 5) * 5); // saltos de 5 min

            spinner.setValue(cal.getTime());
        };

        jSpinnerHoraIni.addChangeListener(listener);
        jSpinnerHoraFin.addChangeListener(listener);
    }

    /**
     * Limpia el campo nombre.
     */
    public void limpiarNombre() {
        jTextFieldActNombre.setText("");
    }

    /**
     * Limpia la descripción.
     */
    public void limpiarDescripcion() {
        jTextAreaActDesc.setText("");
    }

    /**
     * Reinicia las horas a valores por defecto.
     */
    public void limpiarHoras() {
        jSpinnerHoraIni.setValue(new java.util.Date());
        jSpinnerHoraFin.setValue(new java.util.Date());
    }

    /**
     * Reinicia el aforo.
     */
    public void limpiarAforo() {
        jSpinnerActAforo.setValue(1);
    }
}
