SET SERVEROUTPUT ON;

ALTER SESSION SET CONTAINER = XEPDB1;
/
ALTER SESSION SET NLS_DATE_LANGUAGE = 'SPANISH';
/

BEGIN
-- 1. ROLES

INSERT INTO ROL (ID_ROL,NOMBRE_ROL,DESCRIPCION) VALUES (1,'ADMINISTRADOR','Control total');

INSERT INTO ROL (ID_ROL,NOMBRE_ROL,DESCRIPCION) VALUES (2,'USUARIO','Usuario gimnasio');


-- 2. METODOS DE PAGO

INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL,'Efectivo','Pago físico');

INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL,'Tarjeta','Pago tarjeta');

INSERT INTO METODO_PAGO VALUES (SEQ_METODO_PAGO.NEXTVAL,'BIZUM','Pago móvil');


-- 3. USUARIOS ADMIN

INSERT INTO USUARIO (ID_USUARIO,EMAIL,ID_ROL) VALUES (SEQ_USUARIO.NEXTVAL,'admin@fitmanage.com',1);

INSERT INTO USUARIO (ID_USUARIO,EMAIL,ID_ROL) VALUES (SEQ_USUARIO.NEXTVAL,'jantonio@fitmanage.com',1);


-- 4. CLIENTES 

INSERT INTO CLIENTE (ID_CLIENTE,NOMBRE,APELLIDOS,EMAIL,DNI,TELEFONO,DIRECCION,FECHA_ALTA,CUOTA_MENSUAL,ID_USUARIO,ID_ROL,ACTIVO)
VALUES (SEQ_CLIENTE.NEXTVAL,'Laura','García','laura@email.com','12345678A','600111111','Sevilla',SYSDATE,45,NULL,2,'1');

INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'Vicente','Martinez','vicente@email.com','87654321B','600222222','Sevilla',SYSDATE,NULL,45,NULL,2,'1');

INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'Amparo','Llanos','amparo@email.com','23456789A','600333333','Sevilla',SYSDATE,NULL,45,NULL,2,'1');

INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'Cristina','Llanos','cristina@email.com','23456789Z','600444444','Sevilla',SYSDATE,NULL,45,NULL,2,'1');

INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'Miguel','Lopez','miguel@email.com','98755678A','600555555','Sevilla',SYSDATE,NULL,45,NULL,2,'1');

INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'Pedro','Muñoz','pedro@email.com','09654723B','600666666','Sevilla',SYSDATE,NULL,45,NULL,2,'1');

INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'Barbara','Sol','barbara@email.com','32071264T','600777777','Sevilla',SYSDATE,NULL,45,NULL,2,'1');

INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'Daniel','Vazquez','daniel@email.com','98754321Z','600888888','Sevilla',SYSDATE,NULL,45,NULL,2,'1');

INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'Fernando','Garcia','fernando@email.com','42585678A','600999999','Sevilla',SYSDATE,NULL,45,NULL,2,'1');

INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL,'Maria','Knox','maria@email.com','80650321Y','600101010','Sevilla',SYSDATE,NULL,45,NULL,2,'1');


-- 5. DIAS

INSERT INTO DIA VALUES (SEQ_DIA.NEXTVAL,'L','Lunes');

INSERT INTO DIA VALUES (SEQ_DIA.NEXTVAL,'M','Martes');

INSERT INTO DIA VALUES (SEQ_DIA.NEXTVAL,'X','Miércoles');

INSERT INTO DIA VALUES (SEQ_DIA.NEXTVAL,'J','Jueves');

INSERT INTO DIA VALUES (SEQ_DIA.NEXTVAL,'V','Viernes');

INSERT INTO DIA VALUES (SEQ_DIA.NEXTVAL,'S','Sábado');

INSERT INTO DIA VALUES (SEQ_DIA.NEXTVAL,'D','Domingo');


-- 6. ACTIVIDADES 

INSERT INTO ACTIVIDAD VALUES (SEQ_ACTIVIDAD.NEXTVAL,'Spinning','Cardio','18:00','19:00',2);

INSERT INTO ACTIVIDAD VALUES (SEQ_ACTIVIDAD.NEXTVAL,'Yoga','Relax','19:00','20:00',3);

INSERT INTO ACTIVIDAD VALUES (SEQ_ACTIVIDAD.NEXTVAL,'Crossfit','WOD','20:00','21:00',2);

INSERT INTO ACTIVIDAD VALUES (SEQ_ACTIVIDAD.NEXTVAL,'HIIT','Alta intensidad','15:00','15:30',3);

INSERT INTO ACTIVIDAD VALUES (SEQ_ACTIVIDAD.NEXTVAL,'GAP','Piernas','21:00','21:45',2);

INSERT INTO ACTIVIDAD VALUES (SEQ_ACTIVIDAD.NEXTVAL,'Pilates','Core','17:00','18:00',3);

INSERT INTO ACTIVIDAD VALUES (SEQ_ACTIVIDAD.NEXTVAL,'Body Pump','Fuerza','18:00','19:00',2);

INSERT INTO ACTIVIDAD VALUES (SEQ_ACTIVIDAD.NEXTVAL,'Salsa','Baile','18:00','19:00',4);

INSERT INTO ACTIVIDAD VALUES (SEQ_ACTIVIDAD.NEXTVAL,'Espalda-Sana','Postural','19:00','20:00',3);

INSERT INTO ACTIVIDAD VALUES (SEQ_ACTIVIDAD.NEXTVAL,'Halterofilia','Fuerza','19:00','20:00',2);


-- 7. ACTIVIDAD_DIA

INSERT INTO ACTIVIDAD_DIA VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL,(SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE='Spinning'),(SELECT ID_DIA FROM DIA WHERE CODIGO='L'));

INSERT INTO ACTIVIDAD_DIA VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL,(SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE='Yoga'),(SELECT ID_DIA FROM DIA WHERE CODIGO='M'));

INSERT INTO ACTIVIDAD_DIA VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL,(SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE='Crossfit'),(SELECT ID_DIA FROM DIA WHERE CODIGO='X'));

INSERT INTO ACTIVIDAD_DIA VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL,(SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE='HIIT'),(SELECT ID_DIA FROM DIA WHERE CODIGO='J'));

INSERT INTO ACTIVIDAD_DIA VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL,(SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE='GAP'),(SELECT ID_DIA FROM DIA WHERE CODIGO='V'));

INSERT INTO ACTIVIDAD_DIA VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL,(SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE='Pilates'),(SELECT ID_DIA FROM DIA WHERE CODIGO='S'));

INSERT INTO ACTIVIDAD_DIA VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL,(SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE='Body Pump'),(SELECT ID_DIA FROM DIA WHERE CODIGO='D'));

INSERT INTO ACTIVIDAD_DIA VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL,(SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE='Salsa'),(SELECT ID_DIA FROM DIA WHERE CODIGO='M'));

INSERT INTO ACTIVIDAD_DIA VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL,(SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE='Espalda-Sana'),(SELECT ID_DIA FROM DIA WHERE CODIGO='J'));

INSERT INTO ACTIVIDAD_DIA VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL,(SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE='Halterofilia'),(SELECT ID_DIA FROM DIA WHERE CODIGO='V'));



-- 8. PAGOS 

INSERT INTO PAGO (IMPORTE,ID_CLIENTE,ID_METODO_PAGO,CONCEPTO)
SELECT 45, ID_CLIENTE, (SELECT ID_METODO_PAGO FROM METODO_PAGO WHERE NOMBRE_METODO='BIZUM'),'Cuota mensual'
FROM CLIENTE WHERE ROWNUM <= 5;

INSERT INTO PAGO (IMPORTE,ID_CLIENTE,ID_METODO_PAGO,CONCEPTO)
SELECT 3, ID_CLIENTE, (SELECT ID_METODO_PAGO FROM METODO_PAGO WHERE NOMBRE_METODO='Efectivo'),'Bebida'
FROM CLIENTE WHERE ROWNUM <= 5;


-- 9. RESERVAS (10)

INSERT INTO RESERVA (ID_CLIENTE,ID_ACT_DIA,FECHA_CLASE,ESTADO_ACTIVA)
VALUES (
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE='Laura'),
(SELECT ID_ACT_DIA FROM ACTIVIDAD_DIA WHERE ROWNUM=1),
NEXT_DAY(SYSDATE,'LUNES'),
'1'
);

INSERT INTO RESERVA (ID_CLIENTE,ID_ACT_DIA,FECHA_CLASE,ESTADO_ACTIVA)
VALUES (
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE='Vicente'),
(SELECT ID_ACT_DIA FROM ACTIVIDAD_DIA WHERE ROWNUM=1),
NEXT_DAY(SYSDATE,'LUNES'),
'1'
);

-- MARTES
INSERT INTO RESERVA (ID_CLIENTE,ID_ACT_DIA,FECHA_CLASE,ESTADO_ACTIVA)
VALUES (
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE='Amparo'),
(SELECT ID_ACT_DIA FROM ACTIVIDAD_DIA WHERE ROWNUM=1),
NEXT_DAY(SYSDATE,'MARTES'),
'1'
);

INSERT INTO RESERVA (ID_CLIENTE,ID_ACT_DIA,FECHA_CLASE,ESTADO_ACTIVA)
VALUES (
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE='Cristina'),
(SELECT ID_ACT_DIA FROM ACTIVIDAD_DIA WHERE ROWNUM=1),
NEXT_DAY(SYSDATE,'MARTES'),
'1'
);

-- MIÉRCOLES
INSERT INTO RESERVA (ID_CLIENTE,ID_ACT_DIA,FECHA_CLASE,ESTADO_ACTIVA)
VALUES (
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE='Miguel'),
(SELECT ID_ACT_DIA FROM ACTIVIDAD_DIA WHERE ROWNUM=1),
NEXT_DAY(SYSDATE,'MIÉRCOLES'),
'1'
);

INSERT INTO RESERVA (ID_CLIENTE,ID_ACT_DIA,FECHA_CLASE,ESTADO_ACTIVA)
VALUES (
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE='Pedro'),
(SELECT ID_ACT_DIA FROM ACTIVIDAD_DIA WHERE ROWNUM=1),
NEXT_DAY(SYSDATE,'MIÉRCOLES'),
'1'
);

-- JUEVES
INSERT INTO RESERVA (ID_CLIENTE,ID_ACT_DIA,FECHA_CLASE,ESTADO_ACTIVA)
VALUES (
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE='Barbara'),
(SELECT ID_ACT_DIA FROM ACTIVIDAD_DIA WHERE ROWNUM=1),
NEXT_DAY(SYSDATE,'JUEVES'),
'1'
);

INSERT INTO RESERVA (ID_CLIENTE,ID_ACT_DIA,FECHA_CLASE,ESTADO_ACTIVA)
VALUES (
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE='Daniel'),
(SELECT ID_ACT_DIA FROM ACTIVIDAD_DIA WHERE ROWNUM=1),
NEXT_DAY(SYSDATE,'JUEVES'),
'1'
);

-- VIERNES
INSERT INTO RESERVA (ID_CLIENTE,ID_ACT_DIA,FECHA_CLASE,ESTADO_ACTIVA)
VALUES (
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE='Fernando'),
(SELECT ID_ACT_DIA FROM ACTIVIDAD_DIA WHERE ROWNUM=1),
NEXT_DAY(SYSDATE,'VIERNES'),
'1'
);

INSERT INTO RESERVA (ID_CLIENTE,ID_ACT_DIA,FECHA_CLASE,ESTADO_ACTIVA)
VALUES (
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE='Maria'),
(SELECT ID_ACT_DIA FROM ACTIVIDAD_DIA WHERE ROWNUM=1),
NEXT_DAY(SYSDATE,'VIERNES'),
'1'
);

-- FINALIZAR TRANSACCION
DBMS_OUTPUT.PUT_LINE('Script de inserci�n de datos ejecutado correctamente');

COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
                DBMS_OUTPUT.PUT_LINE('No se han insertado datos');

END;
/