package view;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Alejandro
 */
public class FormActividadesJDialog extends javax.swing.JDialog {

    /**
     * Creates new form FormActividadesJDialog
     * @param parent
     * @param modal
     */
    public FormActividadesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setPreferredSize(new Dimension(800, 600));
        setMinimumSize(new Dimension(700, 500));
        setLocationRelativeTo(parent);
        pack();    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableActividades = new javax.swing.JTable();
        jButtonNuevaActividad = new javax.swing.JButton();
        jButtonEliminarActividad = new javax.swing.JButton();
        jButtonModificarActividad = new javax.swing.JButton();
        jButtonActividadesSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin.- Menú de actividades dirigidas");

        jTableActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableActividades);

        jButtonNuevaActividad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNuevaActividad.setText("Publicar Actividad");

        jButtonEliminarActividad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonEliminarActividad.setText("Eliminar Actividad");

        jButtonModificarActividad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonModificarActividad.setText("Modificar Actividad");

        jButtonActividadesSalir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonActividadesSalir.setText("Salir ");
        jButtonActividadesSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActividadesSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("GESTIÓN DE ACTIVIDADES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jButtonActividadesSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonNuevaActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonEliminarActividad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButtonNuevaActividad)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarActividad)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificarActividad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButtonActividadesSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActividadesSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActividadesSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonActividadesSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActividadesSalir;
    private javax.swing.JButton jButtonEliminarActividad;
    private javax.swing.JButton jButtonModificarActividad;
    private javax.swing.JButton jButtonNuevaActividad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableActividades;
    // End of variables declaration//GEN-END:variables

    public JTable getJTableActividades() {
        return jTableActividades;
    }

    public JButton getJButtonNuevaActividad() {
        return jButtonNuevaActividad;
    }

    public JButton getJButtonEditarActividad() {
        return jButtonModificarActividad;
    }

    public JButton getJButtonEliminarActividad() {
        return jButtonEliminarActividad;
    }
}
