/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.Reserva;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import main.AppLauncher;
import util.Session;

/**
 *
 * @author Alejandro
 */
public class ClienteJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClienteJFrame
     */
    public ClienteJFrame() {
        initComponents();
        
                File img = new File("resources/img/Logo_FitManage.png");
        ImageIcon icon = new ImageIcon(img.getAbsolutePath());
        java.awt.Image scaledImage = icon.getImage().getScaledInstance(190,
                180,java.awt.Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        setIconImage(icon.getImage());
        jLabelLogo.setIcon(scaledIcon);
        jLabelLogo.setText("Logo de FitManage");
        
        setSize(1200, 800);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSaludo = new javax.swing.JLabel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonNuevaReserva = new javax.swing.JButton();
        jButtonCancelarReserva = new javax.swing.JButton();
        jButtonDescargarFactura = new javax.swing.JButton();
        jButtonjButtonMisDatos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReservas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de cliente");

        jLabelSaludo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabelSaludo.setText("Panel del cliente ");

        jButtonCerrarSesion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.setActionCommand("jButtonCerrarSesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jButtonNuevaReserva.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonNuevaReserva.setText("Nueva Reserva");

        jButtonCancelarReserva.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonCancelarReserva.setText("Cancelar Reserva");

        jButtonDescargarFactura.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonDescargarFactura.setText("Descargar última factura");

        jButtonjButtonMisDatos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonjButtonMisDatos.setText("Consultar Mis Datos");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Mis actividades reservadas:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Contabilidad: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Reservas: ");

        jTableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableReservas.setName("Mis Reservas"); // NOI18N
        jScrollPane2.setViewportView(jTableReservas);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Consultar mis datos: ");

        jLabelLogo.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonjButtonMisDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonNuevaReserva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonCancelarReserva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 31, Short.MAX_VALUE)))
                                .addGap(70, 70, 70))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDescargarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(96, 96, 96)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabelSaludo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jLabelSaludo)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDescargarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonjButtonMisDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNuevaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
         logout();    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarReserva;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonDescargarFactura;
    private javax.swing.JButton jButtonNuevaReserva;
    private javax.swing.JButton jButtonjButtonMisDatos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelSaludo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableReservas;
    // End of variables declaration//GEN-END:variables
    private void logout() {
        Session.logout();
        dispose();
        AppLauncher.showLogin();
    }

        public JLabel getJLabelSaludo() {
        return jLabelSaludo;
    }
    
    public JButton getJButtonNuevaReserva() {
        return jButtonNuevaReserva;
    }

    public JButton getJButtonCancelarReserva() {
        return jButtonCancelarReserva;
    }

    public JButton getJButtonDescargarFactura() {
        return jButtonDescargarFactura;
    }

    public JButton getJButtonMisDatos() {
        return jButtonjButtonMisDatos;
    }

    public JTable getJTableReservas() {
        return jTableReservas;
    }

    /*public void setReservas(List<Reserva> reservas) {

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Actividad", "Día", "Hora", "Fecha", "Estado"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Reserva r : reservas) {
            model.addRow(new Object[]{
                r.getIdReserva(),
                r.getActividadDia().getActividad().getNombre(),
                r.getActividadDia().getDia().getNombre(),
                r.getActividadDia().getActividad().getHoraInicio()
                + " - " + r.getActividadDia().getActividad().getHoraFin(),
                r.getFechaClase(),
                r.isActiva() ? "ACTIVA" : "CANCELADA"
            });
        }
        jTableReservas.setModel(model);
        jTableReservas.getColumnModel().getColumn(5) // columna "Estado"
                .setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
                    @Override
                    public java.awt.Component getTableCellRendererComponent(
                            javax.swing.JTable table,
                            Object value,
                            boolean isSelected,
                            boolean hasFocus,
                            int row,
                            int column
                    ) {
                        java.awt.Component c = super.getTableCellRendererComponent(
                                table, value, isSelected, hasFocus, row, column
                        );

                        if ("CANCELADA".equals(value)) {
                            c.setForeground(java.awt.Color.RED);
                        } else {
                            c.setForeground(new java.awt.Color(0, 128, 0));
                        }

                        return c;
                    }
                });

        // Ocultar ID (clave interna)
        jTableReservas.removeColumn(
                jTableReservas.getColumnModel().getColumn(0)
        );
    }*/
    public void setReservas(List<Reserva> reservas) {

    DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID", "Actividad", "Día", "Hora", "Fecha", "Estado"},
            0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    java.time.format.DateTimeFormatter formatter =
            java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy");
    for (Reserva r : reservas) {
        String fechaFormateada = r.getFechaClase() != null
                ? r.getFechaClase().format(formatter)
                : "";
        model.addRow(new Object[]{
            r.getIdReserva(),
            r.getActividadDia().getActividad().getNombre(),
            r.getActividadDia().getDia().getNombre(),
            r.getActividadDia().getActividad().getHoraInicio()
            + " - " + r.getActividadDia().getActividad().getHoraFin(),
            fechaFormateada,
            r.isActiva() ? "ACTIVA" : "CANCELADA"
        });
    }

    jTableReservas.setModel(model);
    jTableReservas.getColumnModel().getColumn(5)
            .setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(
                        javax.swing.JTable table,
                        Object value,
                        boolean isSelected,
                        boolean hasFocus,
                        int row,
                        int column
                ) {
                    java.awt.Component c = super.getTableCellRendererComponent(
                            table, value, isSelected, hasFocus, row, column
                    );

                    if ("CANCELADA".equals(value)) {
                        c.setForeground(java.awt.Color.RED);
                    } else {
                        c.setForeground(new java.awt.Color(0, 128, 0));
                    }

                    return c;
                }
            });

    // Ocultar ID
    jTableReservas.removeColumn(
            jTableReservas.getColumnModel().getColumn(0)
    );
}
}
