/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import Model.Actividad;
import Model.Dia;
import java.awt.Dialog;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Alejandro
 */
public class FormActividadJDialog extends javax.swing.JDialog {

    private Integer idActividad;
    private static final DateTimeFormatter TIME_FORMAT
            = DateTimeFormatter.ofPattern("HH:mm");

    /**
     * Creates new form FormActividadJDialog
     */
    public FormActividadJDialog(java.awt.Window parent) {
        super(parent, Dialog.ModalityType.APPLICATION_MODAL);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonActAceptar = new javax.swing.JButton();
        jButtonActCancelar = new javax.swing.JButton();
        jTextFieldActNombre = new javax.swing.JTextField();
        jTextFieldActHoraIni = new javax.swing.JTextField();
        jTextFieldActHoraFin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaActDesc = new javax.swing.JTextArea();
        jSpinnerActAforo = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBoxL = new javax.swing.JCheckBox();
        jCheckBoxX = new javax.swing.JCheckBox();
        jCheckBoxM = new javax.swing.JCheckBox();
        jCheckBoxJ = new javax.swing.JCheckBox();
        jCheckBoxV = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxS = new javax.swing.JCheckBox();
        jCheckBoxD = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin,. Datos de actividad dirigida");

        jButtonActAceptar.setText("Aceptar");

        jButtonActCancelar.setText("Cancelar");
        jButtonActCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActCancelarActionPerformed(evt);
            }
        });

        jTextFieldActHoraFin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextAreaActDesc.setColumns(20);
        jTextAreaActDesc.setRows(5);
        jScrollPane1.setViewportView(jTextAreaActDesc);

        jLabel1.setText("Actividad: ");

        jLabel2.setText("Comienza a las: ");

        jLabel3.setText("Termina a las: ");

        jLabel4.setText("Aforo máx.: ");

        jLabel5.setText("Descripción: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("NUEVA ACTIVDAD DIRIGIDA");

        jCheckBoxL.setText("L");

        jCheckBoxX.setText("X");

        jCheckBoxM.setText("M");

        jCheckBoxJ.setText("J");

        jCheckBoxV.setText("V");

        jLabel7.setText("Días de impartición: ");

        jCheckBoxS.setText("S");

        jCheckBoxD.setText("D");
        jCheckBoxD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldActNombre)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jTextFieldActHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel3)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextFieldActHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(68, 68, 68)
                                                    .addComponent(jCheckBoxL)
                                                    .addGap(1, 1, 1)
                                                    .addComponent(jCheckBoxM)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCheckBoxX)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCheckBoxJ, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCheckBoxV)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addComponent(jButtonActAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jSpinnerActAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonActCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(456, 456, 456)))
                .addComponent(jCheckBoxS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxD)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldActNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldActHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldActHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jSpinnerActAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxL)
                            .addComponent(jCheckBoxM)
                            .addComponent(jCheckBoxX)
                            .addComponent(jCheckBoxJ)
                            .addComponent(jCheckBoxV)
                            .addComponent(jCheckBoxS)
                            .addComponent(jCheckBoxD))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActAceptar)
                    .addComponent(jButtonActCancelar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActCancelarActionPerformed
        dispose();    }//GEN-LAST:event_jButtonActCancelarActionPerformed

    private void jCheckBoxDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActAceptar;
    private javax.swing.JButton jButtonActCancelar;
    private javax.swing.JCheckBox jCheckBoxD;
    private javax.swing.JCheckBox jCheckBoxJ;
    private javax.swing.JCheckBox jCheckBoxL;
    private javax.swing.JCheckBox jCheckBoxM;
    private javax.swing.JCheckBox jCheckBoxS;
    private javax.swing.JCheckBox jCheckBoxV;
    private javax.swing.JCheckBox jCheckBoxX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerActAforo;
    private javax.swing.JTextArea jTextAreaActDesc;
    private javax.swing.JTextField jTextFieldActHoraFin;
    private javax.swing.JTextField jTextFieldActHoraIni;
    private javax.swing.JTextField jTextFieldActNombre;
    // End of variables declaration//GEN-END:variables
public String getJTextFieldActNombre() {
        return jTextFieldActNombre.getText();
    }

    public String getJTextAreaActDesc() {
        return jTextAreaActDesc.getText();
    }

    public LocalTime getJTextFieldActHoraIni() {
        String texto = jTextFieldActHoraIni.getText().trim();

        if (!texto.matches("^\\d{2}:\\d{2}$")) {
            throw new IllegalArgumentException(
                    "La hora de inicio debe tener el formato HH:mm (ej: 09:30)"
            );
        }

        return LocalTime.parse(texto, TIME_FORMAT);
    }

    public LocalTime getJTextFieldActHoraFin() {
        String texto = jTextFieldActHoraFin.getText().trim();

        if (!texto.matches("^\\d{2}:\\d{2}$")) {
            throw new IllegalArgumentException(
                    "La hora de finalización debe tener el formato HH:mm (ej: 09:30)"
            );
        }

        return LocalTime.parse(texto, TIME_FORMAT);
    }

    public int getJSpinnerActAforo() {
        return (int) jSpinnerActAforo.getValue();
    }

    public JButton getJButtonActAceptar() {
        return jButtonActAceptar;
    }

    public JButton getJButtonActCancelar() {
        return jButtonActCancelar;
    }

    public void setActividad(Actividad actividad) {

        this.idActividad = actividad.getIdActividad();
        jTextFieldActNombre.setText(actividad.getNombre());
        jTextAreaActDesc.setText(actividad.getDescripcion());
        jTextFieldActHoraIni.setText(
                actividad.getHoraInicio().toString()
        );
        jTextFieldActHoraFin.setText(
                actividad.getHoraFin().toString()
        );
        jSpinnerActAforo.setValue(actividad.getAforoMaximo());
    }

    public Integer getIdActividad() {
        return idActividad;
    }

    public boolean isLunesSeleccionado() {
        return jCheckBoxL.isSelected();
    }

    public boolean isMartesSeleccionado() {
        return jCheckBoxM.isSelected();
    }

    public boolean isMiercolesSeleccionado() {
        return jCheckBoxX.isSelected();
    }

    public boolean isJuevesSeleccionado() {
        return jCheckBoxJ.isSelected();
    }

    public boolean isViernesSeleccionado() {
        return jCheckBoxV.isSelected();
    }

    public boolean isSabadoSeleccionado() {
        return jCheckBoxS.isSelected();
    }

    public boolean isDomingoSeleccionado() {
        return jCheckBoxD.isSelected();
    }

    public List<Dia> getDiasSeleccionados(List<Dia> todosLosDias) {

        List<Dia> seleccionados = new ArrayList<>();

        for (Dia d : todosLosDias) {
            switch (d.getCodigo()) {
                case "L":
                    if (jCheckBoxL.isSelected()) {
                        seleccionados.add(d);
                    }
                    break;
                case "M":
                    if (jCheckBoxM.isSelected()) {
                        seleccionados.add(d);
                    }
                    break;
                case "X":
                    if (jCheckBoxX.isSelected()) {
                        seleccionados.add(d);
                    }
                    break;
                case "J":
                    if (jCheckBoxJ.isSelected()) {
                        seleccionados.add(d);
                    }
                    break;
                case "V":
                    if (jCheckBoxV.isSelected()) {
                        seleccionados.add(d);
                    }
                    break;
                case "S":
                    if (jCheckBoxS.isSelected()) {
                        seleccionados.add(d);
                    }
                    break;
                case "D":
                    if (jCheckBoxD.isSelected()) {
                        seleccionados.add(d);
                    }
                    break;
            }
        }

        return seleccionados;
    }

    public void marcarDias(List<Dia> dias) {

        // Limpiar primero
        jCheckBoxL.setSelected(false);
        jCheckBoxM.setSelected(false);
        jCheckBoxX.setSelected(false);
        jCheckBoxJ.setSelected(false);
        jCheckBoxV.setSelected(false);
        jCheckBoxS.setSelected(false);
        jCheckBoxD.setSelected(false);

        for (Dia d : dias) {

            if (d == null || d.getCodigo() == null) {
                continue;
            }

            switch (d.getCodigo()) {

                case "L":
                    jCheckBoxL.setSelected(true);
                    break;

                case "M":
                    jCheckBoxM.setSelected(true);
                    break;

                case "X":
                    jCheckBoxX.setSelected(true);
                    break;

                case "J":
                    jCheckBoxJ.setSelected(true);
                    break;

                case "V":
                    jCheckBoxV.setSelected(true);
                    break;

                case "S":
                    jCheckBoxS.setSelected(true);
                    break;

                case "D":
                    jCheckBoxD.setSelected(true);
                    break;

                default:
                    break;
            }
        }
    }
}
