/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import Model.Pago;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author Alejandro
 */
public class FormListadoPagosJDialog extends javax.swing.JDialog {

    /**
     * Creates new form FormListadoPagosJDialog
     */
    public FormListadoPagosJDialog(java.awt.Frame parent, boolean modal, List<Pago> pagos) {
        super(parent, modal);
        initComponents();

        setSize(700, 500);
        setResizable(false);
        setLocationRelativeTo(null);        cargarPagos(pagos);
    }

/**
 * Carga en la tabla el listado de pagos del cliente.
 *
 * <p>
 * Este método formatea la fecha de pago utilizando un formato legible
 * para el usuario final siguiendo el estilo:
 * </p>
 *
 * <pre>
 * "Martes, 29 de enero de 1991"
 * </pre>
 *
 * <p>
 * La fecha se obtiene como {@code LocalDate} desde el modelo {@link Pago}
 * y se formatea mediante {@link DateTimeFormatter}.
 * </p>
 *
 * @param pagos lista de pagos a mostrar en la tabla
 */
private void cargarPagos(List<Pago> pagos) {

    String[] columnas = {"Fecha", "Importe (€)"};
    DefaultTableModel model = new DefaultTableModel(columnas, 0);
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern(
            "EEEE, d 'de' MMMM 'de' yyyy",
            new Locale("es", "ES")
    );
    for (Pago p : pagos) {

        String fechaFormateada = p.getFechaPago().format(formatter);
        fechaFormateada = fechaFormateada.substring(0, 1).toUpperCase()
                + fechaFormateada.substring(1);
        model.addRow(new Object[]{
            fechaFormateada,
            p.getImporte()
        });
    }

    jTableListadoPagos.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCerrarListadoPagos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListadoPagos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin.- Listado de pagos");

        jButtonCerrarListadoPagos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonCerrarListadoPagos.setText("Cerrar");
        jButtonCerrarListadoPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarListadoPagosActionPerformed(evt);
            }
        });

        jTableListadoPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableListadoPagos);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("LISTADO DE PAGOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCerrarListadoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrarListadoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarListadoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarListadoPagosActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarListadoPagosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarListadoPagos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListadoPagos;
    // End of variables declaration//GEN-END:variables
}
