-- 1. Tablespace
CREATE SMALLFILE TABLESPACE FITMANAGE 
DATAFILE 'fitmanage.dbf' 
SIZE 100M 
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- 2. Perfil
CREATE PROFILE FITMANAGE LIMIT
    PASSWORD_LIFE_TIME UNLIMITED;

-- 3. Usuario
CREATE USER FITMANAGE IDENTIFIED BY admin123
DEFAULT TABLESPACE FITMANAGE
PROFILE FITMANAGE;

-- 4. Permisos
GRANT DBA TO FITMANAGE;
GRANT UNLIMITED TABLESPACE TO FITMANAGE;

-- Le damos permisos ilimitados a tu usuario para escribir en él

ALTER USER "FITMANAGE" QUOTA UNLIMITED ON "FITMANAGE";
--------------------------------------------------------
--  DDL for Sequence SEQ_ROL
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_ROL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_METODO_PAGO
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_METODO_PAGO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTE
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_CLIENTE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTE_ESTADO
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_CLIENTE_ESTADO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_ACTIVIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_ACTIVIDAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_DIA
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_DIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_ACTIVIDAD_DIA
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_ACTIVIDAD_DIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_FACTURA
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_FACTURA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_PAGO
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_PAGO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_RESERVA
--------------------------------------------------------

   CREATE SEQUENCE  "FITMANAGE"."SEQ_RESERVA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
--------------------------------------------------------
-- 1. TABLES (Con Tablespace incluido)
--------------------------------------------------------
CREATE TABLE "FITMANAGE"."ROL" (
    "ID_ROL" NUMBER(10,0), 
    "NOMBRE_ROL" VARCHAR2(30) NOT NULL ENABLE, 
    "DESCRIPCION" VARCHAR2(200), 
    PRIMARY KEY ("ID_ROL")
) TABLESPACE "FITMANAGE";

CREATE TABLE "FITMANAGE"."METODO_PAGO" (
    "ID_METODO_PAGO" NUMBER(10,0), 
    "NOMBRE_METODO" VARCHAR2(50) NOT NULL ENABLE, 
    "DESCRIPCION" VARCHAR2(150), 
    PRIMARY KEY ("ID_METODO_PAGO")
) TABLESPACE "FITMANAGE";

CREATE TABLE "FITMANAGE"."USUARIO" (
    "ID_USUARIO" NUMBER(10,0), 
    "EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
    "CONTRASENA_HASH" VARCHAR2(200), 
    "FECHA_CREACION" DATE DEFAULT SYSDATE, 
    "ID_ROL" NUMBER(10,0) NOT NULL ENABLE, 
    PRIMARY KEY ("ID_USUARIO"),
    CONSTRAINT "UQ_USUARIO_EMAIL" UNIQUE ("EMAIL"),
    CONSTRAINT "FK_USUARIO_ROL" FOREIGN KEY ("ID_ROL") REFERENCES "FITMANAGE"."ROL" ("ID_ROL") ENABLE
) TABLESPACE "FITMANAGE";

CREATE TABLE "FITMANAGE"."CLIENTE" (
    "ID_CLIENTE" NUMBER(10,0), 
    "NOMBRE" VARCHAR2(50) NOT NULL ENABLE, 
    "APELLIDOS" VARCHAR2(100), 
    "EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
    "DNI" VARCHAR2(15), 
    "TELEFONO" VARCHAR2(15), 
    "DIRECCION" VARCHAR2(150), 
    "FECHA_ALTA" DATE DEFAULT SYSDATE, 
    "FECHA_PROXIMO_PAGO" DATE, 
    "CUOTA_MENSUAL" NUMBER(6,2) DEFAULT '35', 
    "ID_USUARIO" NUMBER(10,0), 
    "ID_ROL" NUMBER(10,0) DEFAULT '2', 
    "ACTIVO" CHAR(1) DEFAULT '0', 
    CHECK (activo IN ('0','1')) ENABLE, 
    PRIMARY KEY ("ID_CLIENTE"),
    CONSTRAINT "UQ_CLIENTE_EMAIL" UNIQUE ("EMAIL"),
    CONSTRAINT "FK_CLIENTE_ROL" FOREIGN KEY ("ID_ROL") REFERENCES "FITMANAGE"."ROL" ("ID_ROL") ENABLE, 
    CONSTRAINT "FK_CLIENTE_USUARIO" FOREIGN KEY ("ID_USUARIO") REFERENCES "FITMANAGE"."USUARIO" ("ID_USUARIO") ON DELETE CASCADE ENABLE
) TABLESPACE "FITMANAGE";

CREATE TABLE "FITMANAGE"."CLIENTE_ESTADO" (
    "ID_ESTADO" NUMBER(10,0), 
    "ID_CLIENTE" NUMBER(10,0) NOT NULL ENABLE, 
    "FECHA_INICIO" DATE NOT NULL ENABLE, 
    "FECHA_FIN" DATE, 
    "ACTIVO" CHAR(1) NOT NULL ENABLE, 
    CHECK (activo IN ('0','1')) ENABLE, 
    PRIMARY KEY ("ID_ESTADO"),
    CONSTRAINT "FK_ESTADO_CLIENTE" FOREIGN KEY ("ID_CLIENTE") REFERENCES "FITMANAGE"."CLIENTE" ("ID_CLIENTE") ON DELETE CASCADE ENABLE
) TABLESPACE "FITMANAGE";

CREATE TABLE "FITMANAGE"."ACTIVIDAD" (
    "ID_ACTIVIDAD" NUMBER(10,0), 
    "NOMBRE" VARCHAR2(50) NOT NULL ENABLE, 
    "DESCRIPCION" VARCHAR2(200), 
    "HORA_INICIO" VARCHAR2(5), 
    "HORA_FIN" VARCHAR2(5), 
    "AFORO_MAXIMO" NUMBER(3,0), 
    PRIMARY KEY ("ID_ACTIVIDAD")
) TABLESPACE "FITMANAGE";

CREATE TABLE "FITMANAGE"."DIA" (
    "ID_DIA" NUMBER(2,0), 
    "CODIGO" CHAR(1), 
    "NOMBRE" VARCHAR2(10), 
    PRIMARY KEY ("ID_DIA"),
    UNIQUE ("CODIGO")
) TABLESPACE "FITMANAGE";

CREATE TABLE "FITMANAGE"."ACTIVIDAD_DIA" (
    "ID_ACT_DIA" NUMBER(10,0), 
    "ID_ACTIVIDAD" NUMBER(10,0) NOT NULL ENABLE, 
    "ID_DIA" NUMBER(2,0) NOT NULL ENABLE, 
    PRIMARY KEY ("ID_ACT_DIA"),
    CONSTRAINT "FK_ACTDIA_ACT" FOREIGN KEY ("ID_ACTIVIDAD") REFERENCES "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD") ENABLE, 
    CONSTRAINT "FK_ACTDIA_DIA" FOREIGN KEY ("ID_DIA") REFERENCES "FITMANAGE"."DIA" ("ID_DIA") ENABLE
) TABLESPACE "FITMANAGE";

CREATE TABLE "FITMANAGE"."FACTURA" (
    "ID_FACTURA" NUMBER(10,0), 
    "FECHA_EMISION" DATE DEFAULT SYSDATE, 
    "TOTAL" NUMBER(7,2), 
    "ID_METODO_PAGO" NUMBER(10,0), 
    "CONCEPTO" VARCHAR2(255) DEFAULT 'Cuota mensual', 
    PRIMARY KEY ("ID_FACTURA"),
    CONSTRAINT "FK_FACTURA_METODO" FOREIGN KEY ("ID_METODO_PAGO") REFERENCES "FITMANAGE"."METODO_PAGO" ("ID_METODO_PAGO") ENABLE
) TABLESPACE "FITMANAGE";

CREATE TABLE "FITMANAGE"."PAGO" (
    "ID_PAGO" NUMBER(10,0), 
    "FECHA_PAGO" DATE DEFAULT SYSDATE, 
    "IMPORTE" NUMBER(7,2), 
    "ID_CLIENTE" NUMBER(10,0) NOT NULL ENABLE, 
    "ID_METODO_PAGO" NUMBER(10,0), 
    "ID_FACTURA" NUMBER(10,0), 
    "CONCEPTO" VARCHAR2(255), 
    PRIMARY KEY ("ID_PAGO"),
    CONSTRAINT "FK_PAGO_METODO" FOREIGN KEY ("ID_METODO_PAGO") REFERENCES "FITMANAGE"."METODO_PAGO" ("ID_METODO_PAGO") ENABLE, 
    CONSTRAINT "FK_PAGO_FACTURA" FOREIGN KEY ("ID_FACTURA") REFERENCES "FITMANAGE"."FACTURA" ("ID_FACTURA") ENABLE, 
    CONSTRAINT "FK_PAGO_CLIENTE" FOREIGN KEY ("ID_CLIENTE") REFERENCES "FITMANAGE"."CLIENTE" ("ID_CLIENTE") ON DELETE CASCADE ENABLE
) TABLESPACE "FITMANAGE";

CREATE TABLE "FITMANAGE"."RESERVA" (
    "ID_RESERVA" NUMBER(10,0), 
    "ID_CLIENTE" NUMBER(10,0) NOT NULL ENABLE, 
    "ID_ACT_DIA" NUMBER(10,0) NOT NULL ENABLE, 
    "FECHA_CLASE" DATE NOT NULL ENABLE, 
    "FECHA_RESERVA" DATE DEFAULT SYSDATE, 
    "ESTADO_ACTIVA" CHAR(1) DEFAULT '1', 
    CHECK (estado_activa IN ('0','1')) ENABLE, 
    PRIMARY KEY ("ID_RESERVA"),
    CONSTRAINT "FK_RESERVA_ACTDIA" FOREIGN KEY ("ID_ACT_DIA") REFERENCES "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA") ENABLE, 
    CONSTRAINT "FK_RESERVA_CLIENTE" FOREIGN KEY ("ID_CLIENTE") REFERENCES "FITMANAGE"."CLIENTE" ("ID_CLIENTE") ON DELETE CASCADE ENABLE
) TABLESPACE "FITMANAGE";

--------------------------------------------------------
-- 2. INDEXES
--------------------------------------------------------
CREATE INDEX "FITMANAGE"."IDX_ACTDIA_ACT" ON "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACTIVIDAD") TABLESPACE "FITMANAGE";
CREATE INDEX "FITMANAGE"."IDX_ACTDIA_DIA" ON "FITMANAGE"."ACTIVIDAD_DIA" ("ID_DIA") TABLESPACE "FITMANAGE";
CREATE INDEX "FITMANAGE"."IDX_PAGO_CLIENTE" ON "FITMANAGE"."PAGO" ("ID_CLIENTE") TABLESPACE "FITMANAGE";
CREATE INDEX "FITMANAGE"."IDX_RESERVA_CLIENTE" ON "FITMANAGE"."RESERVA" ("ID_CLIENTE") TABLESPACE "FITMANAGE";
-------------------------------------------------------------------------------
-- CREAR LA CONEXION  Y EJECUTAR LOS SIGUIENTES APARTADOS EN LA NUEVA CONEXION
-------------------------------------------------------------------------------
--------------------------------------------------------
-- 3. TRIGGERS
--------------------------------------------------------
CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_ROL_BI" 
BEFORE INSERT ON ROL
FOR EACH ROW
 WHEN (NEW.id_rol IS NULL) BEGIN
  :NEW.id_rol := SEQ_ROL.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_METODO_PAGO_BI" 
BEFORE INSERT ON METODO_PAGO
FOR EACH ROW
 WHEN (NEW.id_metodo_pago IS NULL) BEGIN
  :NEW.id_metodo_pago := SEQ_METODO_PAGO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_USUARIO_BI
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    :NEW.ID_USUARIO := SEQ_USUARIO.NEXTVAL;
  END IF;
  IF :NEW.ID_ROL = 1 THEN
    :NEW.CONTRASENA_HASH := '$2a$12$J3oT7EbHWifnI6yDem1qEeUQuL/rVEBuMP3AJRy8YKqs6uCLt08/e';
  ELSIF :NEW.ID_ROL = 2 THEN
    :NEW.CONTRASENA_HASH := '$2a$12$TXSKSodaN4.kUR0exWBS3eu3TsxdQU9TmKLFJiBWKAwMGSunWJmx6';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_CLIENTE_BI" 
BEFORE INSERT ON CLIENTE
FOR EACH ROW
 WHEN (NEW.id_cliente IS NULL) BEGIN
  :NEW.id_cliente := SEQ_CLIENTE.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_CLIENTE_AFTER_INSERT" 
AFTER INSERT ON CLIENTE
FOR EACH ROW
BEGIN
  INSERT INTO CLIENTE_ESTADO (id_estado, id_cliente, fecha_inicio, activo)
  VALUES (SEQ_CLIENTE_ESTADO.NEXTVAL, :NEW.id_cliente, NVL(:NEW.fecha_alta, SYSDATE), :NEW.activo);
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_CLIENTE_ACTIVO_UPDATE" 
AFTER UPDATE OF activo ON CLIENTE
FOR EACH ROW
 WHEN (OLD.activo IS NOT NULL AND NEW.activo IS NOT NULL AND OLD.activo != NEW.activo) DECLARE
BEGIN
  -- Cerrar estado anterior
  UPDATE CLIENTE_ESTADO
  SET fecha_fin = SYSDATE
  WHERE id_cliente = :OLD.id_cliente
    AND fecha_fin IS NULL;

  -- Insertar nuevo estado
  INSERT INTO CLIENTE_ESTADO (id_estado, id_cliente, fecha_inicio, activo)
  VALUES (SEQ_CLIENTE_ESTADO.NEXTVAL, :NEW.id_cliente, SYSDATE, :NEW.activo);
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_CLIENTE_ESTADO_BI" 
BEFORE INSERT ON CLIENTE_ESTADO
FOR EACH ROW
 WHEN (NEW.id_estado IS NULL) BEGIN
  :NEW.id_estado := SEQ_CLIENTE_ESTADO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_ACTIVIDAD_BI" 
BEFORE INSERT ON ACTIVIDAD
FOR EACH ROW
 WHEN (NEW.id_actividad IS NULL) BEGIN
  :NEW.id_actividad := SEQ_ACTIVIDAD.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_DIA_BI" 
BEFORE INSERT ON DIA
FOR EACH ROW
 WHEN (NEW.id_dia IS NULL) BEGIN
  :NEW.id_dia := SEQ_DIA.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_ACTDIA_BI" 
BEFORE INSERT ON ACTIVIDAD_DIA
FOR EACH ROW
 WHEN (NEW.id_act_dia IS NULL) BEGIN
  :NEW.id_act_dia := SEQ_ACTIVIDAD_DIA.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_FACTURA_BI" 
BEFORE INSERT ON FACTURA
FOR EACH ROW
 WHEN (NEW.id_factura IS NULL) BEGIN
  :NEW.id_factura := SEQ_FACTURA.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_PAGO_BI" 
BEFORE INSERT ON PAGO
FOR EACH ROW
DECLARE
  v_id_factura FACTURA.id_factura%TYPE;
BEGIN
  IF :NEW.id_pago IS NULL THEN
    :NEW.id_pago := SEQ_PAGO.NEXTVAL;
  END IF;

  INSERT INTO FACTURA (
      fecha_emision, total, id_metodo_pago, concepto
  ) VALUES (
      SYSDATE, :NEW.importe, :NEW.id_metodo_pago, :NEW.concepto
  )
  RETURNING id_factura INTO v_id_factura;

  :NEW.id_factura := v_id_factura;
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_PAGO_ACTUALIZA_PROXIMO" 
AFTER INSERT ON PAGO
FOR EACH ROW
BEGIN
    UPDATE CLIENTE
    SET FECHA_PROXIMO_PAGO =
        ADD_MONTHS(
            GREATEST(
                NVL(FECHA_PROXIMO_PAGO, :NEW.FECHA_PAGO),
                :NEW.FECHA_PAGO
            ),
            1
        )
    WHERE ID_CLIENTE = :NEW.ID_CLIENTE;
END;
/

CREATE OR REPLACE TRIGGER "FITMANAGE"."TRG_RESERVA_BI" 
BEFORE INSERT ON RESERVA
FOR EACH ROW
 WHEN (NEW.id_reserva IS NULL) BEGIN
  :NEW.id_reserva := SEQ_RESERVA.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CLIENTE_USUARIO_BI
BEFORE INSERT ON CLIENTE
FOR EACH ROW
DECLARE
    v_id_usuario USUARIO.ID_USUARIO%TYPE;
BEGIN
    IF :NEW.ID_USUARIO IS NULL THEN
        BEGIN
            SELECT ID_USUARIO
            INTO v_id_usuario
            FROM USUARIO
            WHERE EMAIL = :NEW.EMAIL;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                v_id_usuario := SEQ_USUARIO.NEXTVAL;

                INSERT INTO USUARIO (ID_USUARIO, EMAIL, ID_ROL)
                VALUES (v_id_usuario, :NEW.EMAIL, 2);                
        END;

        :NEW.ID_USUARIO := v_id_usuario;
    END IF;
END;
/
------------------------------------------------
-- ADDICIONES POSTERIORES EN FASE DE DESARROLLO
------------------------------------------------
-- restriccion para eliminar actividades con reservas
ALTER TABLE ACTIVIDAD_DIA
ADD CONSTRAINT UK_ACTIVIDAD_DIA UNIQUE (ID_ACTIVIDAD, ID_DIA);
--trigger para actualizar aforos de actividades con estado activa
CREATE OR REPLACE TRIGGER TRG_RESERVA_AFORO_BI
BEFORE INSERT ON RESERVA
FOR EACH ROW
DECLARE
    v_aforo_max NUMBER;
    v_reservas_actuales NUMBER;
    v_existe_reserva NUMBER;
BEGIN

    SELECT a.aforo_maximo
    INTO v_aforo_max
    FROM actividad a
    JOIN actividad_dia ad ON ad.id_actividad = a.id_actividad
    WHERE ad.id_act_dia = :NEW.id_act_dia;

    SELECT COUNT(*)
    INTO v_existe_reserva
    FROM reserva
    WHERE id_cliente = :NEW.id_cliente
      AND id_act_dia = :NEW.id_act_dia
      AND fecha_clase = :NEW.fecha_clase
      AND estado_activa = '1';
	IF v_existe_reserva > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'Ya tienes una reserva para esta actividad en esa fecha'
        );
    END IF;
	
	SELECT COUNT(*)
    INTO v_reservas_actuales
    FROM reserva
    WHERE id_act_dia = :NEW.id_act_dia
      AND fecha_clase = :NEW.fecha_clase
      AND estado_activa = '1';
	    IF v_reservas_actuales >= v_aforo_max THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'No hay plazas disponibles para esta actividad en la fecha seleccionada'
        );
    END IF;
    
END;
/

ALTER TABLE PAGO ADD CONSTRAINT chk_concepto_pago CHECK (concepto 
IN (
    'Cuota mensual',
    'Bebida',
    'Alquiler de toalla'
));
COMMIT;
--si no esta ya nullable
ALTER TABLE CLIENTE MODIFY ID_USUARIO NULL;

--borramos esta constraint para modificarla
ALTER TABLE CLIENTE DROP CONSTRAINT FK_CLIENTE_USUARIO; 

--nueva constraint relacionando cliente con usuario para borrado settee null
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID_USUARIO)
ON DELETE SET NULL;

--trigger que crea el usuario de nuevo al reactivar el cliente y le asigna contraseña
CREATE OR REPLACE TRIGGER TRG_CLIENTE_ACTIVAR_USUARIO
BEFORE UPDATE OF activo ON CLIENTE
FOR EACH ROW
WHEN (OLD.activo = 0 AND NEW.activo = 1)
DECLARE
    v_id_usuario USUARIO.ID_USUARIO%TYPE;
BEGIN

    IF :NEW.id_usuario IS NULL THEN

        BEGIN
            SELECT ID_USUARIO
            INTO v_id_usuario
            FROM USUARIO
            WHERE EMAIL = :NEW.EMAIL;

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                v_id_usuario := SEQ_USUARIO.NEXTVAL;

                INSERT INTO USUARIO (
                    ID_USUARIO,
                    EMAIL,
                    ID_ROL,
                    CONTRASENA_HASH
                )
                VALUES (
                    v_id_usuario,
                    :NEW.EMAIL,
                    2,
                    '$2a$12$M7TyKyRK0ytz0CVFsMRWl.OHqjQlZVnqaavzROj76irUkd.Vs82gS'
                );
        END;

        :NEW.id_usuario := v_id_usuario;

    END IF;

END;
/
--elimina usuario con cliente inactivo
CREATE OR REPLACE TRIGGER TRG_CLIENTE_DESACTIVAR_USUARIO
AFTER UPDATE OF activo ON CLIENTE
DECLARE
BEGIN
    DELETE FROM USUARIO
    WHERE id_usuario IN (
        SELECT id_usuario
        FROM CLIENTE
        WHERE activo = 0
        AND id_usuario IS NOT NULL
    );
END;
/
COMMIT;