--------------------------------------------------------
-- SCRIPT DE INSERCIÓN DE DATOS DE PRUEBA - FITMANAGE
--------------------------------------------------------
-- 1. ROLES
INSERT INTO "FITMANAGE"."ROL" ("ID_ROL", "NOMBRE_ROL", "DESCRIPCION") 
VALUES (SEQ_ROL.NEXTVAL, 'ADMINISTRADOR', 'Control total del sistema');
INSERT INTO "FITMANAGE"."ROL" ("ID_ROL", "NOMBRE_ROL", "DESCRIPCION") 
VALUES (SEQ_ROL.NEXTVAL, 'USUARIO', 'Usuario regular del gimnasio');

-- 2. MÉTODOS DE PAGO
INSERT INTO "FITMANAGE"."METODO_PAGO" ("ID_METODO_PAGO", "NOMBRE_METODO", "DESCRIPCION") 
VALUES (SEQ_METODO_PAGO.NEXTVAL, 'Efectivo', 'Pago en metálico en recepción');
INSERT INTO "FITMANAGE"."METODO_PAGO" ("ID_METODO_PAGO", "NOMBRE_METODO", "DESCRIPCION") 
VALUES (SEQ_METODO_PAGO.NEXTVAL, 'Tarjeta', 'Tarjeta de crédito o débito');
INSERT INTO "FITMANAGE"."METODO_PAGO" ("ID_METODO_PAGO", "NOMBRE_METODO", "DESCRIPCION") 
VALUES (SEQ_METODO_PAGO.NEXTVAL, 'BIZUM', 'Transferencia bancaria instantanea');

-- 3. USUARIOS (Vinculados a sus roles)
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'admin@fitmanage.com', 'admin123', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'ADMINISTRADOR'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'jantonio@fitmanage.com', 'admin123', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'ADMINISTRADOR'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'laura.cliente@email.com', '12345678a', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'vicente.cliente@email.com', '12345678a', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'amparo.cliente@email.com', '12345678a', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'cristina.cliente@email.com', '12345678a', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'miguel.cliente@email.com', '12345678a', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'pedro.cliente@email.com', '12345678a', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'barbara.cliente@email.com', '12345678a', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'daniel.cliente@email.com', '12345678a', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'fernando.cliente@email.com', '12345678a', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'));
INSERT INTO "FITMANAGE"."USUARIO" ("ID_USUARIO", "EMAIL", "CONTRASENA_HASH", "ID_ROL") 
VALUES (SEQ_USUARIO.NEXTVAL, 'maria.cliente@email.com', '12345678a', (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'));

-- 4. CLIENTES 
-- (Al ejecutar esto, el trigger TRG_CLIENTE_AFTER_INSERT creará registros en CLIENTE_ESTADO)
INSERT INTO "FITMANAGE"."CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDOS", "EMAIL", "DNI", "TELEFONO", "DIRECCION", "CUOTA_MENSUAL", "ID_USUARIO", "ID_ROL", "ACTIVO") 
VALUES (SEQ_CLIENTE.NEXTVAL, 'Laura', 'García López', 'laura.cliente@email.com', '12345678A', '600111222', 'Calle Mayor 1, Sevilla', 45.00, NULL,(SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'), '1');
INSERT INTO "FITMANAGE"."CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDOS", "EMAIL", "DNI", "TELEFONO", "DIRECCION", "CUOTA_MENSUAL", "ID_USUARIO", "ID_ROL", "ACTIVO") 
VALUES (SEQ_CLIENTE.NEXTVAL, 'Vicente', 'Martínez', 'vicente.cliente@email.com', '87654321B', '600333444', 'Avenida Sol 45, Sevilla', 45.00, NULL, (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'), '1');
INSERT INTO "FITMANAGE"."CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDOS", "EMAIL", "DNI", "TELEFONO", "DIRECCION", "CUOTA_MENSUAL", "ID_USUARIO", "ID_ROL", "ACTIVO") 
VALUES (SEQ_CLIENTE.NEXTVAL, 'Amparo', 'Llanos Fayos', 'amparo.cliente@email.com', '23456789A', '610110220', 'Calle Mayor 3, Sevilla', 45.00, NULL, (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'), '1');
INSERT INTO "FITMANAGE"."CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDOS", "EMAIL", "DNI", "TELEFONO", "DIRECCION", "CUOTA_MENSUAL", "ID_USUARIO", "ID_ROL", "ACTIVO") 
VALUES (SEQ_CLIENTE.NEXTVAL, 'Cristina', 'Llanos Fayos', 'cristina.cliente@email.com', '23456789AZ', '670358474', 'Avenida Sol 45, Sevilla', 45.00, NULL, (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'), '1');
INSERT INTO "FITMANAGE"."CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDOS", "EMAIL", "DNI", "TELEFONO", "DIRECCION", "CUOTA_MENSUAL", "ID_USUARIO", "ID_ROL", "ACTIVO") 
VALUES (SEQ_CLIENTE.NEXTVAL, 'Miguel', 'López Garrido', 'miguel.cliente@email.com', '98755678A', '630221982', 'Avda Montevideo 100, Sevilla', 45.00, NULL, (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'), '1');
INSERT INTO "FITMANAGE"."CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDOS", "EMAIL", "DNI", "TELEFONO", "DIRECCION", "CUOTA_MENSUAL", "ID_USUARIO", "ID_ROL", "ACTIVO") 
VALUES (SEQ_CLIENTE.NEXTVAL, 'Pedro', 'Muñoz Quesada', 'pedro.cliente@email.com', '09654723B', '622356404', 'Camino Soleá 11, Sevilla', 45.00, NULL, (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'), '1');
INSERT INTO "FITMANAGE"."CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDOS", "EMAIL", "DNI", "TELEFONO", "DIRECCION", "CUOTA_MENSUAL", "ID_USUARIO", "ID_ROL", "ACTIVO") 
VALUES (SEQ_CLIENTE.NEXTVAL, 'Barbara', 'Sol Martínez', 'barbara.cliente@email.com', '32071264T', '721002692', 'Camino Ponferrda 18, Sevilla', 45.00, NULL, (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'), '1');
INSERT INTO "FITMANAGE"."CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDOS", "EMAIL", "DNI", "TELEFONO", "DIRECCION", "CUOTA_MENSUAL", "ID_USUARIO", "ID_ROL", "ACTIVO") 
VALUES (SEQ_CLIENTE.NEXTVAL, 'Daniel', 'Vázquez Gil', 'daniel.cliente@email.com', '98754321Z', '620353436', 'Avenida Platón 45, Sevilla', 45.00, NULL, (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'), '1');
INSERT INTO "FITMANAGE"."CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDOS", "EMAIL", "DNI", "TELEFONO", "DIRECCION", "CUOTA_MENSUAL", "ID_USUARIO", "ID_ROL", "ACTIVO") 
VALUES (SEQ_CLIENTE.NEXTVAL, 'Fernando', 'García-Toledo Pérez', 'fernando.cliente@email.com', '42585678A', '615011852', 'Calle Majuelo 158, Sevilla', 45.00, NULL, (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'), '1');
INSERT INTO "FITMANAGE"."CLIENTE" ("ID_CLIENTE", "NOMBRE", "APELLIDOS", "EMAIL", "DNI", "TELEFONO", "DIRECCION", "CUOTA_MENSUAL", "ID_USUARIO", "ID_ROL", "ACTIVO") 
VALUES (SEQ_CLIENTE.NEXTVAL, 'María', 'Knoxville', 'maria.cliente@email.com', '80650321Y', '720383454', 'Avenida Andalucía 45, Sevilla', 45.00, NULL, (SELECT ID_ROL FROM ROL WHERE NOMBRE_ROL = 'USUARIO'), '1');

-- 5. DÍAS DE LA SEMANA
INSERT INTO "FITMANAGE"."DIA" ("ID_DIA", "CODIGO", "NOMBRE") VALUES (SEQ_DIA.NEXTVAL, 'L', 'Lunes');
INSERT INTO "FITMANAGE"."DIA" ("ID_DIA", "CODIGO", "NOMBRE") VALUES (SEQ_DIA.NEXTVAL, 'M', 'Martes');
INSERT INTO "FITMANAGE"."DIA" ("ID_DIA", "CODIGO", "NOMBRE") VALUES (SEQ_DIA.NEXTVAL, 'X', 'Miércoles');
INSERT INTO "FITMANAGE"."DIA" ("ID_DIA", "CODIGO", "NOMBRE") VALUES (SEQ_DIA.NEXTVAL, 'J', 'Jueves');
INSERT INTO "FITMANAGE"."DIA" ("ID_DIA", "CODIGO", "NOMBRE") VALUES (SEQ_DIA.NEXTVAL, 'V', 'Viernes');
INSERT INTO "FITMANAGE"."DIA" ("ID_DIA", "CODIGO", "NOMBRE") VALUES (SEQ_DIA.NEXTVAL, 'S', 'Sábado');
INSERT INTO "FITMANAGE"."DIA" ("ID_DIA", "CODIGO", "NOMBRE") VALUES (SEQ_DIA.NEXTVAL, 'D', 'Domingo');

-- 6. ACTIVIDADES
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'Spinning', 'Ciclo indoor de alta intensidad', '18:00', '19:00', 5);
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'Yoga', 'Hatha yoga para todos los niveles', '19:00', '20:00', 3);
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'Crossfit', 'Entrenamiento funcional WOD', '20:00', '21:00', 4);
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'HIIT', 'Entrenamiento interválico de alta intensidad', '15:00', '15:30', 5);
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'Espalda sana', 'Secuencia de estiramientos para mejora postural', '19:00', '20:00', 3);
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'GAP', 'Glúteos, abdomen y piernas', '21:00', '21:45', 4);
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'Body Pump', 'Coreografía para tonifiación general', '18:00', '19:00', 5);
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'Pilates', 'Método pilates para todos los niveles', '17:00', '18:00', 3);
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'Tecnificación de carrea', 'Ejercicios de atletismo', '15:00', '16:00', 4);
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'Salsa', 'Ritmos procedentes de Colombia', '18:00', '19:00', 5);
INSERT INTO "FITMANAGE"."ACTIVIDAD" ("ID_ACTIVIDAD", "NOMBRE", "DESCRIPCION", "HORA_INICIO", "HORA_FIN", "AFORO_MAXIMO") 
VALUES (SEQ_ACTIVIDAD.NEXTVAL, 'Intro. a la halterofilia', 'Ejercicios de fuerza máxima', '19:00', '20:00', 3);

-- 7. ACTIVIDADES POR DÍA 
-- Spinning 
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'Spinning'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'L')); 
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'Spinning'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'X'));
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'Spinning'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'V'));
-- Yoga los Martes y Jueves 19 A 20
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'Yoga'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'M')); 
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'Yoga'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'J'));
-- Crossfit 
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'Crossfit'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'L')); 
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'Crossfit'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'X'));
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'Crossfit'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'V'));
-- HITT
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'HIIT'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'M')); 
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'HIIT'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'J'));
INSERT INTO "FITMANAGE"."ACTIVIDAD_DIA" ("ID_ACT_DIA", "ID_ACTIVIDAD", "ID_DIA") VALUES (SEQ_ACTIVIDAD_DIA.NEXTVAL, (SELECT ID_ACTIVIDAD FROM ACTIVIDAD WHERE NOMBRE LIKE 'HIIT'), (SELECT ID_DIA FROM DIA WHERE CODIGO = 'S'));

-- 8. PAGOS 
-- (El trigger TRG_PAGO_BI creará la FACTURA, y TRG_PAGO_ACTUALIZA_PROXIMO actualizará la fecha en CLIENTE)
INSERT INTO "FITMANAGE"."PAGO" ("ID_PAGO", "IMPORTE", "ID_CLIENTE", "ID_METODO_PAGO", "CONCEPTO") 
VALUES (SEQ_PAGO.NEXTVAL, (SELECT CUOTA_MENSUAL FROM CLIENTE WHERE NOMBRE LIKE 'Laura'), (SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE LIKE 'Laura'), (SELECT ID_METODO_PAGO FROM METODO_PAGO WHERE NOMBRE_METODO LIKE 'BIZUM'), 'Cuota mensual');
INSERT INTO "FITMANAGE"."PAGO" ("ID_PAGO", "IMPORTE", "ID_CLIENTE", "ID_METODO_PAGO", "CONCEPTO") 
VALUES (SEQ_PAGO.NEXTVAL, 3, (SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE LIKE 'Laura'), (SELECT ID_METODO_PAGO FROM METODO_PAGO WHERE NOMBRE_METODO LIKE 'Tarjeta'), 'Alquiler de toalla');
INSERT INTO "FITMANAGE"."PAGO" ("ID_PAGO", "IMPORTE", "ID_CLIENTE", "ID_METODO_PAGO", "CONCEPTO") 
VALUES (SEQ_PAGO.NEXTVAL, (SELECT CUOTA_MENSUAL FROM CLIENTE WHERE NOMBRE LIKE 'David'), (SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE LIKE 'David'), (SELECT ID_METODO_PAGO FROM METODO_PAGO WHERE NOMBRE_METODO LIKE 'Tarjeta'), 'Cuota mensual');
INSERT INTO "FITMANAGE"."PAGO" ("ID_PAGO", "IMPORTE", "ID_CLIENTE", "ID_METODO_PAGO", "CONCEPTO") 
VALUES (SEQ_PAGO.NEXTVAL, 3, (SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE LIKE 'Laura'), (SELECT ID_METODO_PAGO FROM METODO_PAGO WHERE NOMBRE_METODO LIKE 'Efectivo'), 'Bebida');

-- 9. RESERVAS
-- Establecemos los nombres de los días de la semana para las fechas en español
ALTER SESSION SET NLS_DATE_LANGUAGE = 'SPANISH';
-- Laura reserva Spinning el prox. lunes
INSERT INTO "FITMANAGE"."RESERVA" ("ID_RESERVA", "ID_CLIENTE", "ID_ACT_DIA", "FECHA_CLASE", "ESTADO_ACTIVA") 
VALUES (SEQ_RESERVA.NEXTVAL, (SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE LIKE 'Laura'), (SELECT ID_ACT_DIA FROM ACTIVIDAD A JOIN ACTIVIDAD_DIA D ON A.ID_ACTIVIDAD = D.ID_ACTIVIDAD WHERE A.NOMBRE = 'Spinning' AND D.ID_DIA = (SELECT ID_DIA FROM DIA WHERE CODIGO = 'L')),(SELECT NEXT_DAY(SYSDATE, 'LUNES') FROM DUAL) , '1');
-- Vicente reserva Yoga el prox. martes
INSERT INTO "FITMANAGE"."RESERVA" ("ID_RESERVA", "ID_CLIENTE", "ID_ACT_DIA", "FECHA_CLASE", "ESTADO_ACTIVA") 
VALUES (SEQ_RESERVA.NEXTVAL, (SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE LIKE 'Vicente'),(SELECT ID_ACT_DIA FROM ACTIVIDAD A JOIN ACTIVIDAD_DIA D ON A.ID_ACTIVIDAD = D.ID_ACTIVIDAD WHERE A.NOMBRE = 'Yoga' AND D.ID_DIA = (SELECT ID_DIA FROM DIA WHERE CODIGO = 'M')),(SELECT NEXT_DAY(SYSDATE, 'MARTES') FROM DUAL), 1);
--Amparo reserva HIIT el prox. jueves
INSERT INTO "FITMANAGE"."RESERVA" ("ID_RESERVA", "ID_CLIENTE", "ID_ACT_DIA", "FECHA_CLASE", "ESTADO_ACTIVA") 
VALUES (SEQ_RESERVA.NEXTVAL, (SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE LIKE 'Amparo'), (SELECT ID_ACT_DIA FROM ACTIVIDAD A JOIN ACTIVIDAD_DIA D ON A.ID_ACTIVIDAD = D.ID_ACTIVIDAD WHERE A.NOMBRE = 'HIIT' AND D.ID_DIA = (SELECT ID_DIA FROM DIA WHERE CODIGO = 'J')),(SELECT NEXT_DAY(SYSDATE, 'JUEVES') FROM DUAL), 1);

-- Guardamos los cambios
COMMIT;