-- SELECCION SESION
ALTER SESSION SET CONTAINER = XEPDB1;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Sesión cambiada');
END;
/

-- ELIMINAR USUARIO SI EXISTE
BEGIN
    EXECUTE IMMEDIATE 'DROP USER FITMANAGE CASCADE';
EXCEPTION
    WHEN OTHERS THEN 
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Usuario FITMANAGE borrado');
END;
/

-- ELIMINAR PERFIL SI EXISTE
BEGIN
    EXECUTE IMMEDIATE 'DROP PROFILE FITMANAGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2380, -2382) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Perfil FITMANAGE borrado');
END;
/

-- CREAR PERFIL
BEGIN
    BEGIN
        EXECUTE IMMEDIATE '
            CREATE PROFILE FITMANAGE LIMIT
                SESSIONS_PER_USER UNLIMITED
                FAILED_LOGIN_ATTEMPTS UNLIMITED
                PASSWORD_LIFE_TIME UNLIMITED
        ';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -2376 THEN
                EXECUTE IMMEDIATE '
                    CREATE PROFILE FITMANAGE LIMIT
                        SESSIONS_PER_USER UNLIMITED
                ';
            ELSE
                RAISE;
            END IF;
    END;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Perfil FITMANAGE creado');
END;
/

-- CREAR USUARIO (SIN TABLESPACE)
CREATE USER FITMANAGE IDENTIFIED BY admin123
PROFILE FITMANAGE;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Usuario FITMANAGE creado');
END;
/

-- PRIVILEGIOS
GRANT CONNECT, RESOURCE, DBA TO FITMANAGE;
/

ALTER USER FITMANAGE QUOTA UNLIMITED ON USERS;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Permisos asignados correctamente');
END;
/